# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vecnorm <- function(x) {
    .Call('_GraphAlgorithms_vecnorm', PACKAGE = 'GraphAlgorithms', x)
}

vektorzugriff <- function(xy, i) {
    .Call('_GraphAlgorithms_vektorzugriff', PACKAGE = 'GraphAlgorithms', xy, i)
}

vergl <- function(x, y) {
    .Call('_GraphAlgorithms_vergl', PACKAGE = 'GraphAlgorithms', x, y)
}

toVec <- function(x, i) {
    .Call('_GraphAlgorithms_toVec', PACKAGE = 'GraphAlgorithms', x, i)
}

isNA <- function(x) {
    .Call('_GraphAlgorithms_isNA', PACKAGE = 'GraphAlgorithms', x)
}

excl <- function(xy, vertices, excluded, i) {
    .Call('_GraphAlgorithms_excl', PACKAGE = 'GraphAlgorithms', xy, vertices, excluded, i)
}

Gab <- function(Gabriel, edges1, edges2) {
    .Call('_GraphAlgorithms_Gab', PACKAGE = 'GraphAlgorithms', Gabriel, edges1, edges2)
}

filterIndexVector <- function(indexVector, excluded) {
    .Call('_GraphAlgorithms_filterIndexVector', PACKAGE = 'GraphAlgorithms', indexVector, excluded)
}

getAdjList <- function(npts, UniqXY) {
    .Call('_GraphAlgorithms_getAdjList', PACKAGE = 'GraphAlgorithms', npts, UniqXY)
}

fastPdist2 <- function(Ar, Br) {
    .Call('_GraphAlgorithms_fastPdist2', PACKAGE = 'GraphAlgorithms', Ar, Br)
}

BrokenGabrielEdgesX <- function(x, edges) {
    .Call('_GraphAlgorithms_BrokenGabrielEdgesX', PACKAGE = 'GraphAlgorithms', x, edges)
}

